version: '3.7'
volumes:
  aidbox_pg_data: {}
services:
  aidbox_db:
    image: healthsamurai/aidboxdb:16.1
    volumes:
    - aidbox_pg_data:/data:delegated
    ports:
    - 6432:5432
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: '5432'
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: 9ZeQDaNUAO
  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on:
    - aidbox_db
    ports:
    - 8080:8080
    environment:
      AIDBOX_TERMINOLOGY_SERVICE_BASE_URL: https://tx.fhir.org/r4
      AIDBOX_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      AIDBOX_FHIR_SCHEMA_VALIDATION: true
      AIDBOX_CREATED_AT_URL: https://aidbox.app/ex/createdAt
      AIDBOX_CLIENT_SECRET: uqBkONT45D
      AIDBOX_CORRECT_AIDBOX_FORMAT: true
      AIDBOX_ADMIN_PASSWORD: 1YrZTAWmro
      AIDBOX_COMPLIANCE: enabled
      BOX_SEARCH_FHIR__COMPARISONS: true
      PGHOST: aidbox_db
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: '#{:fhir-datetime}'
      PGUSER: aidbox
      AIDBOX_PORT: 8080
      PGDATABASE: aidbox
      PGPASSWORD: 9ZeQDaNUAO
      PGPORT: '5432'
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SEARCH_ENGINE: jsonpath 
